### ISSUE TITLE
后端启动报错

### ISSUE THREAD

**Issue by loilih** [bitxx/go-admin#3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1272c0a]

**Comment by bitxx** [comment]
有具体报错位置吗，麻烦贴一下完整的错误日志？
启动不成功，一般只有配置异常会出现

**Comment by loilih** [comment]
直接go run main.go还是什么

**Comment by loilih** [comment]
我直接 go run main.go

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x842c0a]

goroutine 1 [running]:
github.com/bitxx/logger/logbase.(*Helper).Infof(0x0, {0x1120ee6, 0x3}, {0xc00076e050, 0x1, 0x1})
        C:/Users/yunfe/go/pkg/mod/github.com/bitxx/logger@v1.6.2/logbase/helper.go:24 +0x4a
go-admin/core/utils/log.Infof(...)
        D:/golang/go-admin-master/core/utils/log/log.go:37
go-admin/core/cmd.tip()
        D:/golang/go-admin-master/core/cmd/cobra.go:35 +0x11f
go-admin/core/cmd.glob..func1(0xc000e1cc00?, {0x2311c20?, 0x4?, 0x1122495?})
        D:/golang/go-admin-master/core/cmd/cobra.go:22 +0x25
github.com/spf13/cobra.(*Command).ValidateArgs(...)
        C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1096
github.com/spf13/cobra.(*Command).execute(0x22977a0, {0xc00004a0c0, 0x0, 0x0})
        C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:909 +0x693
github.com/spf13/cobra.(*Command).ExecuteC(0x22977a0)
        C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
go-admin/core/cmd.Execute()
        D:/golang/go-admin-master/core/cmd/cobra.go:44 +0x1a
main.main()
        D:/golang/go-admin-master/main.go:17 +0xf
exit status 2

**Comment by bitxx** [comment]
> 我直接 go run main.go
> 
> panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0x842c0a]
> 
> goroutine 1 [running]: github.com/bitxx/logger/logbase.(*Helper).Infof(0x0, {0x1120ee6, 0x3}, {0xc00076e050, 0x1, 0x1}) C:/Users/yunfe/go/pkg/mod/github.com/bitxx/logger@v1.6.2/logbase/helper.go:24 +0x4a go-admin/core/utils/log.Infof(...) D:/golang/go-admin-master/core/utils/log/log.go:37 go-admin/core/cmd.tip() D:/golang/go-admin-master/core/cmd/cobra.go:35 +0x11f go-admin/core/cmd.glob..func1(0xc000e1cc00?, {0x2311c20?, 0x4?, 0x1122495?}) D:/golang/go-admin-master/core/cmd/cobra.go:22 +0x25 github.com/spf13/cobra.(*Command).ValidateArgs(...) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1096 github.com/spf13/cobra.(*Command).execute(0x22977a0, {0xc00004a0c0, 0x0, 0x0}) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:909 +0x693 github.com/spf13/cobra.(*Command).ExecuteC(0x22977a0) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 github.com/spf13/cobra.(*Command).Execute(...) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 go-admin/core/cmd.Execute() D:/golang/go-admin-master/core/cmd/cobra.go:44 +0x1a main.main() D:/golang/go-admin-master/main.go:17 +0xf exit status 2

你是编译启动，也一样要带启动参数。

**Comment by bitxx** [comment]
> 我直接 go run main.go
> 
> panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0x842c0a]
> 
> goroutine 1 [running]: github.com/bitxx/logger/logbase.(*Helper).Infof(0x0, {0x1120ee6, 0x3}, {0xc00076e050, 0x1, 0x1}) C:/Users/yunfe/go/pkg/mod/github.com/bitxx/logger@v1.6.2/logbase/helper.go:24 +0x4a go-admin/core/utils/log.Infof(...) D:/golang/go-admin-master/core/utils/log/log.go:37 go-admin/core/cmd.tip() D:/golang/go-admin-master/core/cmd/cobra.go:35 +0x11f go-admin/core/cmd.glob..func1(0xc000e1cc00?, {0x2311c20?, 0x4?, 0x1122495?}) D:/golang/go-admin-master/core/cmd/cobra.go:22 +0x25 github.com/spf13/cobra.(*Command).ValidateArgs(...) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1096 github.com/spf13/cobra.(*Command).execute(0x22977a0, {0xc00004a0c0, 0x0, 0x0}) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:909 +0x693 github.com/spf13/cobra.(*Command).ExecuteC(0x22977a0) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 github.com/spf13/cobra.(*Command).Execute(...) C:/Users/yunfe/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 go-admin/core/cmd.Execute() D:/golang/go-admin-master/core/cmd/cobra.go:44 +0x1a main.main() D:/golang/go-admin-master/main.go:17 +0xf exit status 2

你是编译启动，也需要配置启动参数的，需要加上"server"或者 "-c 配置位置" 
可参考README.md的二进制启动方式，逻辑一样。

下面是在idea的IDE中编译启动的配置：
![WX20240511-092434](https://github.com/bitxx/go-admin/assets/13200618/adf6aa0a-f3e6-49c8-8d62-413b4e9130c3)

**Comment by loilih** [comment]
好的,谢谢

**Comment by loilih** [comment]
导入数据库,生成代码,接口状态码:404

![image](https://github.com/bitxx/go-admin/assets/52526576/7ba8ff34-0321-4b98-8811-0d8a2239cfa7)

**Comment by bitxx** [comment]
> 导入数据库,生成代码,接口状态码:404
> 
> ![image](https://private-user-images.githubusercontent.com/52526576/329766089-7ba8ff34-0321-4b98-8811-0d8a2239cfa7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxOTcwMTEsIm5iZiI6MTczNDE5NjcxMSwicGF0aCI6Ii81MjUyNjU3Ni8zMjk3NjYwODktN2JhOGZmMzQtMDMyMS00Yjk4LTg4MTEtMGQ4YTIyMzljZmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE3MTgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOTg0YjFmNTAxZTJkMThjYTU1ZWE0Y2IxNzBmN2U5OTIyMDFmOTY1YzZjYWFiMWUwZjhhMzVjMTdjMjIyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jKS-mSYC4Zjjwz4oAM8PZIrL2QGayCldnthwSIInkw0)

该问题已处理
