### ISSUE TITLE
前端启动报错

### ISSUE THREAD

**Issue by 10D24D** [bitxx/go-admin#4]
将npm镜像源换成国内的 https://registry.npmmirror.com 或 https://npmmirror.com/mirrors/ 
虽然npm install成功了，但是npm run起不来

一堆sass报错

不知道作者使用的是node哪个版本呢？

**Comment by bitxx** [comment]
> 将npm镜像源换成国内的 https://registry.npmmirror.com 或 https://npmmirror.com/mirrors/ 虽然npm install成功了，但是npm run起不来
> 
> 一堆sass报错
> 
> 不知道作者使用的是node哪个版本呢？

我用的这个源：https://registry.npm.taobao.org/
node我用22.10和20.18都运行成功了。
昨天新电脑部署`npm install --force --verbose`，一直提示：`failed with CERT_HAS_EXPIRED`，就设置了个：
npm config set strict-ssl false
然后再install，就好了。
npm run dev 的时候，会报一堆错，但最后还是能成功启动。

后续打算用新技术重构下前端，目前vue2勉强能运行起来就好
