### ISSUE TITLE
前端运行报错

### ISSUE THREAD

**Issue by raosheng** [bitxx/go-admin#5]
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/d3966171-45b3-4ebc-aea2-2a6717958f4b">

**Comment by bitxx** [comment]
这问题没遇到过，看着像是前端依赖安装或者node环境的问题

**Comment by watsonhaw5566** [comment]
应该是你的 node 版本太高了。

**Comment by bitxx** [comment]
后续将切换新版前端，目前vue2版只作最基本维护
